### ISSUE TITLE
深度拷贝不生效,thrownet.sf.cglib.beans.BulkBeanException: com.alibaba.tamper.object.NestedSrcMappingObject cannot be cast to com.alibaba.tamper.object.NestedTargetMappingObject

### ISSUE THREAD

**Issue by summaryNZH** [alibaba/tamper#10]
将注解去掉后或抛异常,并不能深度拷贝 

public void testCopy_ok() {
        SrcMappingObject srcRef = new SrcMappingObject();
        srcRef.setIntegerValue(1);
        srcRef.setIntValue(1);
        srcRef.setName("ljh");
        srcRef.setStart(true);

        // NestedSrcMappingObject nestedSrcRef = new NestedSrcMappingObject();
        // nestedSrcRef.setBigDecimalValue(BigDecimal.ONE);
        // srcRef.setMapping(nestedSrcRef);

        TargetMappingObject targetRef = new TargetMappingObject();// 测试一下mapping到一个Object对象
        srcCopyer.copy(srcRef, targetRef);
        assertEquals(targetRef.getIntegerValue(), srcRef.getIntegerValue());
        assertEquals(targetRef.getIntValue(), srcRef.getIntValue());
        assertNull(targetRef.getTargetName());// 为null，因为属性不匹配
        assertEquals(targetRef.isStart(), srcRef.isStart());

        SrcMappingObject newSrcRef = new SrcMappingObject();// 反过来再mapping一次
        targetCopyer.copy(targetRef, newSrcRef);
        assertEquals(newSrcRef.getIntegerValue(), targetRef.getIntegerValue());
        assertEquals(newSrcRef.getIntValue(), targetRef.getIntValue());
        assertNull(newSrcRef.getName());// 为null，因为属性不匹配
        assertEquals(newSrcRef.isStart(), targetRef.isStart());
    }

**Comment by agapple** [comment]
中间的注释那段应该是定义了嵌套mapping的逻辑，去掉了之后直接按照原类型复制了，所以有cast异常
